# Uncomment the next line to define a global platform for your project
  platform :ios, '12.0'

target 'dicSWUnary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'

  pod 'Then'

  pod 'lottie-ios' 
  # Pods for dicSWUnary

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'CodableFirebase'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'FirebaseFirestore'
  pod 'TinyConstraints', '~> 4.0.0'
  pod 'JGProgressHUD', '~> 2.0.3'


  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings.delete 'ARCHS'
      end
    end
  end



end
