# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'dicSWUnary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'

  pod 'Then'
  # Pods for dicSWUnary

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
       config.build_settings.delete 'ARCHS'
      end
    end
  end



end
